### ISSUE TITLE
Enable logging

### ISSUE THREAD

**Issue by hojberg** [udark/underdark-android#15]
I'm having trouble seeing any logging.
What is supposed to happen when `Underdark.configureLogging(true);` is called?

**Comment by virl** [comment]
@hojberg It logs using SLF4J.

**Comment by hojberg** [comment]
@virl I'm not too familiar with SLF4J. From the docs https://www.slf4j.org/android/ it seems that all I should be doing was adding `compile 'eu.lp0.slf4j:slf4j-android:1.7.25-0'` to my Gradle file.

Do you know of any additional configuration needed for Underdark?

**Comment by virl** [comment]
@hojberg As I understand, think dependency just routes logging to logcat. If that's what you need, you can use it.

**Comment by hojberg** [comment]
@virl I do need it in logcat, but even after adding `compile 'eu.lp0.slf4j:slf4j-android:1.7.25-0'` and `Underdark.configureLogging(true)` I still see no logs from Underdark :(

**Comment by hojberg** [comment]
Got this working by configuring SLF4J correctly for DEBUG.
