### ISSUE TITLE
Bluetooth LE advertising doesn't work even with Peripheral mode Device

### ISSUE THREAD

**Issue by Buddabread** [udark/underdark-android#21]
Hello,

this Framework works great with Wifi, but it's not possible to connect devices over Bluetooth.
The devices can't find each other, do you have any idea for a solution?

Cheers
Budda

**Comment by virl** [comment]
@Buddabread What Android version do you use?

**Comment by Buddabread** [comment]
@virl Android 6.0 without LE Periperal and Android 8.1 which supports Periperal Mode

**Comment by virl** [comment]
@Buddabread Android 8 currently can only connect to pre-Android8 devices.
But for that pre-Android8 device should support BLE Peripheral mode.

**Comment by Buddabread** [comment]
With Android Version <8 Bluetooth LE works great. 
Do you have any updates scheduled to support Android 8?

**Comment by virl** [comment]
@Buddabread It will be known in nearby months, depending on quality of BLE stack in Android 8.x

**Comment by Buddabread** [comment]
Are there any news with the quality of the BLE stack in Android 8?

**Comment by virl** [comment]
@Buddabread Yes, BLE improves in Android 8, but via Bluetooth Android 8 devices can only connect to pre-Android 8 devices for now.

**Comment by normdoow** [comment]
Thanks for the great library! When will support for Android 8 devices be added?

**Comment by virl** [comment]
@normdoow I'm currently working on iOS Bluetooth support (ETA 1-1.5 months) and will work on Android support after that.

**Comment by Riaxter** [comment]
Your library is super cool, but still there are some connection problem. 
HUAWEI H Phone(CAM-L32 API 23) and Samsung Galaxy S7(SM-G930K API 26) cannot discover each other while Samsung Galaxy Alpha(SM-G850K API21) can discover two devices, Is this same issue??

**Comment by virl** [comment]
@Riaxter Thanks.
Does this phones have BLE Peripheral hardware support?
It can be checked via https://play.google.com/store/apps/details?id=com.kyriakosalexandrou.bluetoothsupportcheck&hl=en

**Comment by normdoow** [comment]
What is the status of Android 8 device support? Thanks!

**Comment by virl** [comment]
@normdoow Greetings!
Currently I'm working on improving iOS version.
As for Android, Google broke/deprecated the Bluetooth API that I used, so it will require some time to find and test alternatives.

**Comment by normdoow** [comment]
Thanks @virl!

**Comment by normdoow** [comment]
@virl What is the status of this update for Android?
