### ISSUE TITLE
How to change the Activity without loosing Connection

### ISSUE THREAD

**Issue by Buddabread** [udark/underdark-android#22]
Hi there,

could you tell me how to change the Activity without loosing Connection while using Bluetooth BLE?

Cheers
Buddabread

**Comment by virl** [comment]
@Buddabread Library work doesn't depend on Activity lifecycle unless you make it so in your app.

**Comment by Buddabread** [comment]
You are right, I did a mistake in my Lifecycle! Thanks. Was just wondering whats the function of the TransportNeedsActivity Method.

**Comment by virl** [comment]
@Buddabread That method no longer used and will be deprecated.
