### ISSUE TITLE
Transmission is not working between iOS and Android

### ISSUE THREAD

**Issue by adonishong** [udark/underdark-android#7]
At first, appreciate for your guys fantastic work. ^_^

Solidarity are installed in an iPhone 6S Plus, iPad Air, and another three Android devices. The three Android devices could see each other, send data, text without any issue, but none of them could see any iOS devices. The two iOS devices also could talk to each other, however none of android devices could be discovered by them.
Android devices go with Android 5 and 6; iOS devices go with iOS 10.

BTW, does underdark communicate with BLE and Wifi at same time? And what kind of wifi tech do you use? Wifi-direct? Or normal ad-hoc based wifi?

**Comment by virl** [comment]
@adonishong 
Bluetooth between iOS and Android is impossible.
As for wifi, only access point wifi is supported.
